### ISSUE TITLE
ionic2 - enhancement(modal) - add cssClass property to modal options

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#10020]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
Currently, you cannot pass in a cssClass name into the modalOptions object as you can do on alerts, popovers, etc.

**Expected behavior:**
I would like to be able to pass in a cssClass into modalOptions.

**Comment by mhartington** [comment]
I'm assuming you want to do custom style if you present a page as a modal?

**Comment by wbhob** [comment]
Just put it in your modal sass file.

**Comment by zakton5** [comment]
@mhartington Yes, essentially
@wbhob I want to style the modal container, so putting in the modal's sass file won't have any effect.

**Comment by mhartington** [comment]
I don't think we'd add this for 2.0 final, but you could get something by just targeting the component in scss.


so `my-modal-page.scss`


```scss

.modal-wrapper my-modal-page{
  // custom styles that will only be applied to my modal page component
}
```

**Comment by zakton5** [comment]
@mhartington That will not work, because what I really want to achieve here is styling the `.modal-wrapper` itself, not the page contents. Basically, based on the modal, I want to make it larger, smaller, or full screen. Currently there is no way to do that for modals, unlike popovers, etc.

Also, why would you close this? Just because it can't be done in time for 2.0 final doesn't mean it should not be done eventually...

**Comment by wbhob** [comment]
Mike gave you a solution. That DOES resize your actual modal, not the content. It doesn't need to be in 2.0 final because the solution is right there. Please try it before saying it doesn't work.

**Comment by zakton5** [comment]
I had already tried it before even posting this issue. It doesn't work as desired. The following is Ionic's CSS for the modal-wrapper, which is what I want to change, but only for one specific modal.

```css
.modal-wrapper {
    position: absolute;
    top: calc(50% - (600px/2));
    left: calc(50% - (600px/2));
    width: 600px;
    height: 600px;
}
```

Doing something like Mike suggested, such as below, does not resize the wrapper but only the page content itself, which in turn is not even positioned correctly due to the above css that `modal-wrapper` already has.

```css
.modal-wrapper my-modal-page {
    width: 768px;
    height: 1024px;
}
```

What would really be desirable is to apply a class just as one would do for a `Popover`, which I have just tested again and does work.

```css
.modal-wrapper.full-screen-modal {
    position: relative;
    width: 100%;
    height:100%;
}
```
