### ISSUE TITLE
Nibbled words on ion-item

### ISSUE THREAD

**Issue by calebeaires** [driftyco/ionic#11360]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
css property [padding] h2:first-child is bitting words when using H2, H3 (...)

**Related code:**
```css
[padding] h1:first-child, [padding] h2:first-child, [padding] h3:first-child, [padding] h4:first-child, [padding] h5:first-child, [padding] h6:first-child {
    margin-top: -.3rem;
}
```

**How I fix it:**
```css
[padding] h1:first-child, [padding] h2:first-child, [padding] h3:first-child, [padding] h4:first-child, [padding] h5:first-child, [padding] h6:first-child {
    margin-top: 0;
}
```
