### ISSUE TITLE
Item chevron icon no longer in use in ionic.css ?

### ISSUE THREAD

**Issue by jgoux** [driftyco/ionic#1149]
Hi,
it seems that the chevron icon automatically added with .list a.item is no longer included in the styles.
I'd like know if it's a bug or if it's wanted. (The chevron icon is still in use in the documentation here : http://ionicframework.com/docs/components/#item-dividers
I use ionic nightly, and I had to add it manually to my own app.css file : 

``` css
.list a.item:after {
    -webkit-font-smoothing: antialiased;
    font-smoothing: antialiased;
    position: absolute;
    top: 50%;
    right: 11px;
    display: block;
    margin-top: -8px;
    color: #ccc;
    content: "\f125";
    text-transform: none;
    font-weight: normal;
    font-style: normal;
    font-variant: normal;
    font-size: 16px;
    font-family: 'Ionicons';
    line-height: 1;
    speak: none;
}
```
