### ISSUE TITLE
Material Tab highlight is on wrong side of tab when using multiple tab sets

### ISSUE THREAD

**Issue by dudeofawesome** [driftyco/ionic#11608]
**Ionic version:**
[x] **3.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
Here is a screenshot of the issue
![image](https://cloud.githubusercontent.com/assets/1683595/25938516/56b42252-35e4-11e7-88aa-a6d0cfd3226b.png)

As you can see, the bottom bank of `Tab`s has the highlight on the top, where it belongs. The top bank of `Tab`s also has the highlight on the top, instead of on the bottom.

It appears this is caused by the inner `Tab` set inheriting the CSS intended for the outer set.

If I disable this rule:
```css
.tabs-md[tabsHighlight=true][tabsPlacement=bottom] .tab-highlight {
  top: 0;
}
```
then the highlight for both `Tab` sets

**Expected behavior:**
`Tabs` components should be able to have independent highlight locations.

**Steps to reproduce:**
http://embed.plnkr.co/E7YrlL/

**Related code:**

```css
.tabs-md[tabsHighlight=true][tabsPlacement=bottom] .tab-highlight {
  top: 0;
}
```

**Other information:**

**Ionic info:**

```
Cordova CLI: 6.3.1
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v6.10.3
Xcode version: Xcode 8.2.1 Build version 8C1002
```
