### ISSUE TITLE
Retina borders

### ISSUE THREAD

**Issue by ohh2ahh** [driftyco/ionic#1659]
I noticed that the bottom border of the header bar is only 1 px on retina devices - perfect! Do you plan to "retinafy" all your elements? I didn't find anything on https://waffle.io/driftyco/ionic.

I'm using this CSS (pretty similar to your's) for retina borders for a while now and it works great. And with Sass it's quite easy, but I don't have to tell you this :wink:

``` CSS
/* Non-Retina */
.element {
  border: 1px solid black;
}

/* Retina */
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .element {
    border: none;
    background-image:
      linear-gradient(to top, transparent 0%, transparent 50%, black 50%, black 100%),
      linear-gradient(to right, transparent 0%, transparent 50%, black 50%, black 100%),
      linear-gradient(to bottom, transparent 0%, transparent 50%, black 50%, black 100%),
      linear-gradient(to left, transparent 0%, transparent 50%, black 50%, black 100%);
    background-position: top, right, bottom, left;
    background-size: 100% 1px, 1px 100%;
    background-repeat: no-repeat;
  }
}
```
