### ISSUE TITLE
center item options button

### ISSUE THREAD

**Issue by mickaelmarq** [driftyco/ionic#1939]
Hi,

I want to propose a way to center verticaly the item option buttons : 

``` scss
.item-options {

  .button {
    line-height: 0;
  }

  .button:before {
    content: " ";
    height: 50%;
    display: block;
  }
}
```

![suppr](https://cloud.githubusercontent.com/assets/2026965/3832033/ef96a802-1d99-11e4-90e8-717dcedc4cb9.png)
