### ISSUE TITLE
[PopOver height]   in beta 11, the popover height is fixed 

### ISSUE THREAD

**Issue by sjtufjh** [driftyco/ionic#1963]
http://codepen.io/anon/pen/Bhgpd

**Comment by EricDosReis** [comment]
It's a bad solution, because I have to set the height of popover in each View that use a popover. Heigh auto is the HTML natural behavior.

Here is simple solution by weeman:

http://forum.ionicframework.com/t/popover-sizing/8251/8

```css
   ion-popover-view {
  height: auto !important;
}

ion-popover-view ion-content {
  position: relative !important;
}

.platform-android ion-popover-view {
  margin-top: 10px !important;
}
```

Guys update this feature.
