### ISSUE TITLE
Slidebox 

### ISSUE THREAD

**Issue by mathieudutour** [driftyco/ionic#223]
The slidebox example at http://ionicframework.com/docs/angularjs/views/slide-box/ is not working : the slide have just a height of 20px.

I had to add 

``` css
width: 100%;
height: 100%;
```

to .slide-box and .slide-box-slides (ionic.css:3925)

and add 

``` css
.box {
        width: 100%;
        height: 100%;
        color: #fff;
}
.box h1 {
        position: absolute;
        top: 50%;
        width: 100%;
        margin-top: -50px;
        color: #fff;
        font-size: 60px;
        text-align: center;
        font-weight: bold;
}
```

to another css
