### ISSUE TITLE
Align .bar padding and .pull-right button position 

### ISSUE THREAD

**Issue by yankustefan** [driftyco/ionic#2514]
Hi 

I made a custom height and padding for the .bar and ran into an css "inconvenience".

Why don't we apply the .bar padding to the button position for below?

```css
// Place the last button in a bar on the right of the bar
  .title + .button:last-child,
  > .button + .button:last-child,
  > .button.pull-right,
  .buttons.pull-right,
  .title + .buttons {
    position: absolute;
    top: 5px;
    right: 5px;
    bottom: 5px;
  }
```

I guess we could replace the static 5px with: the Sass variable $bar-padding-portrait.
(Whats the difference of $bar-padding-portrait and $bar-padding-landscape anyway?)

maybe also 

```css
  .button-bar + .button,
  .button + .button-bar {
    margin-left: 5px;
  }
```

What do you think?
