### ISSUE TITLE
right-buttons in ion-nav-bar not right

### ISSUE THREAD

**Issue by pascalwhoop** [driftyco/ionic#2564]
Hey guys. First of all great framework !!!!

check this:
http://plnkr.co/edit/gk0NzPqbyYN8FIKWyESL?p=preview

Am I doing something wrong or is the right-buttons class just not taking?

I manipulated your ionic.css from this:

``` css
.bar .title + .button:last-child, .bar > .button + .button:last-child, .bar > .button.pull-right, .bar .buttons.pull-right, .bar .title + .buttons{
    position: absolute;
    top: 5px;
    right: 5px;
    bottom: 5px; }
```

to this:

``` css
.bar .title + .button:last-child, .bar > .button + .button:last-child, .bar > .button.pull-right, .bar .buttons.pull-right, .bar .title + .buttons, .right-buttons {
    position: absolute;
    top: 5px;
    right: 5px;
    bottom: 5px; }
```

Maybe it's a mistake of mine but if not then maybe change that :)

Greetings from Germany :)
