### ISSUE TITLE
Please review the Ionicons font-face definition

### ISSUE THREAD

**Issue by oliversalzburg** [driftyco/ionic#2599]
I'm also experiencing the issue reported at https://github.com/driftyco/ionicons/issues/144, looked into the `@font-face` declaration and was slightly confused.

We're using Ionicons with our Ionic Framework app, and I feel like the `font-face` declaration is counter-productive in this use case (which, to my understanding, is the primary use case of the font).

First of all, I agree with @mowcixo, I don't see how the query on the URL has any benefit when being used in an app bundle. And even if the behavior on Windows Phone 8 is a bug in mobile IE 11, if removing the query from the `src` attribute allows the font to be used on the platform, why not consider changing it? After all, the current definition even includes `#iefix`.

Second, the `src` attribute seems unnecessarily verbose. It is my understanding that `.eot` is included *on the web* for IE8 compatibility, something that should have no relevance in the Ionic framework.
I guess, the `.ttf` enables support Android <4.4, so it is probably required, but should be ordered below the `.woff` IMHO.
I don't see the need for the `.svg`, as all browsers that support `.svg` fonts, also support WOFF. To my understanding, this also holds true on the web.

Please keep in mind that all font variants are usually packaged into the app bundle and contribute to the overall size. The `.svg` and `.eot` weigh 380 KB which might not be required in the package.

For testing purposes, I slimmed down the `font-face` to:
```css
@font-face {
  font-family: "Ionicons";
  src: url("../fonts/ionicons.woff") format("woff"), url("../fonts/ionicons.ttf") format("truetype");
  font-weight: normal;
  font-style: normal; }
```

Which worked great on BlackBerry 10 and Windows Phone 8 (yes, I *do* realize that I tested only on platforms you *don't* support).

I'd be interested to hear your thoughts on this.
