### ISSUE TITLE
The nav-view-transition attribute doesn't always disappear

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2641]
Yet another apparent race condition: the nav-view-transition attribute does not always disappear in the last nightly (27/11/14). It is especially visible when the navbar also has a .has-tabs-top, because of the following css property :

```css
[nav-view-transition="android"] [history-cursor="after-root"] > .has-tabs-top {
  top: 44px; }
```

Which moves the navbar in front of the tabs, leaving a big white space at the top of the page.
