### ISSUE TITLE
Allow for side menu to be "hidden"

### ISSUE THREAD

**Issue by lokkilok** [driftyco/ionic#2682]
Some native components may require the Ionic application to have a transparent area, notably the Google Maps plugin. The ionic (left) side menu however is always there "under" the side-menu-content. Opening the menu simply (and elegantly!) works by translating (moving) the content element sideways.
Would it be possible to include an option that allows the side menu to be "hidden", i.e. for it to take up no space in the document layout at all, whenever it is closed ?

A solution might be to set the style.visibility to "hidden" when the menu is closed and to set it back to "visible" right before it is opened. All of this could be under control of a new attribute (option) on the ion-side-menu directive, e.g. "hide-when-closed='true'".

**Comment by blckshrk** [comment]
Hey,

Personally, I found an elegant solution (right menu) : 
```css
.menu.menu-right {
    transform: translate3d(100%, 0, 0) !important;
}

.menu-open {
    .menu.menu-right {
        transform: translate3d(0, 0, 0) !important;
    }
}
```
