### ISSUE TITLE
Navbar / Content zIndex

### ISSUE THREAD

**Issue by arcanis** [driftyco/ionic#2689]
The `.bar` class has a zIndex 9, and the `.scroll-content-false, .menu .scroll-content.scroll-content-false` a zIndex 11. So, if we want to have a transparent header (by not adding the `.has-header` class to the content and setting a transparent background to the header), the content will be put in front of the navbar, effectively hiding it.

Easily workaroundable, but still :)

For reference, here is my workaround:

```css
.bar {
    z-index: 12;
}

.popover-backdrop, .popover {
    z-index: 13;
}

.bar-transparent {
    background: none;
}

.bar-transparent + ion-content {
    top: 0;
}
```
