### ISSUE TITLE
Popover always 280px high

### ISSUE THREAD

**Issue by PureSpider** [driftyco/ionic#2748]
https://github.com/driftyco/ionic/blob/master/release/css/ionic.css#L4031
This height never gets updated, which leads to a too high popup when only a few items are in it.

My popover template:
```HTML
<ion-popover-view>
	<ion-content>
		<ion-list>
			<ion-item ng-click="logout()">
				Abmelden
			</ion-item>
		</ion-list>
	</ion-content>
</ion-popover-view>
```

**Comment by tomchiverton** [comment]
It seems to be by design based, which makes no sense to me. You can easily end up with cut off items...

**Comment by PureSpider** [comment]
...or a lot of blank space if you don't display "enough" items.

**Comment by mestremuten** [comment]
This is a workaround using CSS class `popover-fit` on `<ion-popover-view>` element:

```css
.popover.popover-fit {
    height: auto;

    .scroll-content {
        position: relative;
        display: block;
        max-height: $popover-height;
    }
}
```

But it would be great stuff to improve it in this way: sizing and positioning.
