### ISSUE TITLE
Cant scroll to end - padding missing

### ISSUE THREAD

**Issue by jonlil** [driftyco/ionic#2781]
Here is the issue
http://codepen.io/anon/pen/raLZKR

1) Set ionic to beta8
2) Scroll to end
3) Set ionic to beta14
4) Try scroll to end

Between beta8 and beta14 the bottom padding for ion-scroll seam to disappeared.

Solution

```css
.has-tabs .scroll { padding-bottom: 46px; }
```
