### ISSUE TITLE
List card in ion-list with href breaks css

### ISSUE THREAD

**Issue by divyenduz** [driftyco/ionic#2841]
Hi There,

I have 2 list cards popping into a ion-list directive. Getting populated by ng-repeat.

While it works find when ion-item does not have a href. When I add a href to the ion-item directive, I am able to see some unwanted padding on the right side of list card

The supporting codepens are :- 
(the line number 19 is changed for adding/removing href)

1. Without href - http://codepen.io/divyenduz/pen/xbRENo
It looks fine
![screenshot from 2015-01-02 18 15 23](https://cloud.githubusercontent.com/assets/746482/5596124/65272fac-92ab-11e4-991b-e5afc076ee8b.png)

2. With href - http://codepen.io/divyenduz/pen/YPpGby
There is some additional padding on the right
![screenshot from 2015-01-02 18 17 45](https://cloud.githubusercontent.com/assets/746482/5596130/b0cb9b6e-92ab-11e4-98e1-c2d5ec941fe1.png)

See the place where mouse pointer is in image.

You might want to make the visible area of codepen smaller to make it look like a mobile. It is easier to see the problem then.

I am on stable beta 14 on my local. Codepen is on nightly, can see the issue on both places.

Let me know if I could explain it better in any way.

Thanks

**Comment by drewrygh** [comment]
Hmm, I'm not sure how common it is to use a card inside of a list item like this. The item is being detected as a complex item since it has a link, and is reserving the extra room on the right for swipe buttons, such as [ion-option-button](http://ionicframework.com/docs/api/directive/ionOptionButton/).

 If you just want a list of card and don't need any of the list/item functionality, you'd be better off just using `ng-repeat` over your list cards, without using ion-list or ion-item. Adding a check to remove this extra padding if the item contains a card would be simple, but it would mean an extra DOM query on every item, which would hurt performance quite a bit.

**Comment by divyenduz** [comment]
Thank for getting back. 

Using the card in list is just a prototype. Later on it would look like this:
![screenshot from 2015-01-05 14 08 08](https://cloud.githubusercontent.com/assets/746482/5610888/69344c8e-94e4-11e4-80d1-3f98601930e5.png)

So, that would be custom css.

I have a long list of items, so, I was planning to use collection-repeat later on but I bumped into this issue. So, not using ion-list won't be possible in this case.

As well, I feel that something like cards in list could be common i.e. when you are making something that looks like Facebook feed. What say ?

I am not sure about what to do about this. I would settle for the best way to handle this.

Thanks a ton :)

**Comment by divyenduz** [comment]
Anyone on this ? I don't want ionitron to come out and close this one for being old :(

**Comment by mhartington** [comment]
For ion-items that have hrefs on them, we're doing a bit more styling and some work in the directive. 
If there is an href, we'll create new `item-content` element, and apply specific styling to that. 

_items with hrefs_
```css
.item-complex .item-content, .item-radio .item-content {
  position: relative;
  z-index: 2;
  padding: 16px 49px 16px 16px;
  border: none;
  background-color: #fff;
}
```


_items without hrefs_
```css
.item {
  border-color: #ddd;
  background-color: #fff;
  color: #444;
  position: relative;
  z-index: 2;
  display: block;
  margin: -1px;
  padding: 16px;
  border-width: 1px;
  border-style: solid;
  font-size: 16px;
}
```

The solution would be to change the padding on the complex item to match the normal item.

http://codepen.io/mhartington/pen/emrQOX
