### ISSUE TITLE
perf: ion-list very slow (scrolling) when I have changed to 1.0.0 beta 14

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic#2896]
```html
<ion-view title="Events">
  <ion-nav-buttons side="left">
    <button menu-toggle="left"class="button button-icon icon ion-navicon"></button>
  </ion-nav-buttons>
  <ion-content>
	<ion-refresher
		pulling-text="Pull to refresh..."
		on-refresh="doRefresh()"
		refreshing-text="Refreshing!"
        refreshing-icon="ion-loading-c">
	</ion-refresher>
	<ion-list>
	  <ion-item 
	  collection-repeat="row in rows"
	  collection-item-height="160"
	  ng-class="rowClass(row)"
	  ng-click="navigate(row)" ng-style="{'width':'100%', 'height':'160px'}">
		<h2><b>Id: {{row.id}} Subject: {{row.subject}}<b></h2>
		<h2>Customer: {{row.customercontact}} {{row.customerlocation.customer.name}} {{row.customerlocation.fulladdress}}</h2>
		<h2>Creation: {{row.date}}</h2>
		<h2>Assigned: {{row.assigneduser.username}}</h2>
		<h2>Status: {{row.eventstatus.name}} Level: <b>{{row.eventlevel.name}}<b/></h2>
		<h2>Tracks: <b>{{row.trackscount}}<b/></h2>
		<ion-option-button class="button-assertive" ng-click="edit(row)">Edit</ion-option-button>
		<ion-option-button class="button-positive" ng-click="delete(row)">Delete</ion-delete-button>
	  </ion-item>
	</ion-list>
	<ion-infinite-scroll
    on-infinite="loadMore()"
    distance="10%">
  </ion-infinite-scroll>
  </ion-content>
</ion-view>
```

```js
.controller('EventsCtrl',function($scope, $stateParams, $ionicTabsDelegate, $location, eventsService, $ionicListDelegate, $q) {	
	$scope.rowClass = function(currentObj) {
		if(currentObj) {
			var classToAdd = "";
			if (currentObj.eventlevel.id === 1) { // critic
				classToAdd += "LevelCritic";
			} else if (currentObj.eventlevel.id === 2) { // high
				classToAdd += "LevelHigh";
			} else if (currentObj.eventlevel.id === 3) { // medium
				classToAdd += "LevelMedium";
			} else if (currentObj.eventlevel.id === 4) { // low
				classToAdd += "LevelLow";
			} else if (currentObj.eventlevel.id === 6) { // proactive
				classToAdd += "LevelProActive";
			} else { // N/A
				classToAdd += "LevelNA";
			}
			if (currentObj.isslaexcluded === true) {
				classToAdd += " ThirdPartyText";
			}
		}
		return classToAdd;
	}
	
	$scope.navigate = function(row) {
		$location.path("/app/events/" + row.id);
	};
	$scope.moreDataCanBeLoaded = true;
	$scope.page = 1;	
	
	$scope.edit = function(item) {
		$ionicListDelegate.closeOptionButtons();
	};
	$scope.delete = function(item) {
		angular.forEach($scope.rows, function(obj, index){
			if(obj.id == item.id) {
				$scope.rows.splice(index, 1);
				$ionicListDelegate.closeOptionButtons();
				return;
			}
		});
	};
	
	$scope.doRefresh = function() {
		$scope.$broadcast('scroll.refreshComplete');
	};
	
	$scope.$on('scroll.refreshComplete', function(event, args) {
		$scope.getEvents(1);
	});
	
	$scope.getEvents = function(page) {
		var deferred = $q.defer();
	
		eventsService.getEvents(page).then(function (results) {
			
			if(page == 1) {
				$scope.page = 1;
				$scope.rows = results.rows;
			}
			else {
				$scope.rows.push.apply($scope.rows, results.rows);
			}

			
			$scope.page = $scope.page + 1;
			deferred.resolve(results);
		});
		
		return deferred.promise;
	}
	
	$scope.loadMore = function() {
		$scope.getEvents($scope.page).then(function(results) {
			console.log("broadcast");
			$scope.$broadcast('scroll.infiniteScrollComplete');
			
			if($scope.page == results.total) {
				$scope.moreDataCanBeLoaded = false;
			}
		});
	};
})
```

```css
.list .item-content 
{
height: 100%;
background-color: inherit !important;
}

/*#region Events*/
.LevelCritic
{
    background: #f5e9eb !important;
}

.LevelHigh
{
    background: #fbeded !important;
}

.LevelMedium
{
    background: #fdf7ed !important;
}

.LevelLow
{
    background: #fffbea !important;
}

.LevelNA
{
    background: #f9f9f9 !important;
}

.LevelProActive {
    background: #fff !important;
}
/*#endregion */
```
