### ISSUE TITLE
bug: “active” class does not work in <ion-item href=“”>

### ISSUE THREAD

**Issue by sgon00** [driftyco/ionic#3050]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Please check the code:
http://codepen.io/anon/pen/PwOQwR

```html
<ion-item class="item-dark active" nav-clear ng-click="login()">
 Login
</ion-item>
<ion-item class="item-dark active" nav-clear href="#">
Browse
</ion-item>
```

`active` class works when the `<ion-item>` does not have `href` attribute.
When `<ion-item>` has the `href` attribute, it will add `<a>` inside ion-item and `<a>`'s background color will override `active` background color with:

```css
.item-complex.item-dark > .item-content {
  border-color: #111;
  background-color: #444;
  color: #fff;
}
```

To workaround this issue, I have to add the following css style to override `<a>` background color again:

```css
.item-complex.item-dark.active > .item-content {
    border-color: #000;
    background-color: #262626;
}
```
