### ISSUE TITLE
bug: Header can be scrolled out of viewport on WP8

### ISSUE THREAD

**Issue by oliversalzburg** [driftyco/ionic#3095]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>By slowly scrolling up, you can move a fixed header out of the viewport.

We work around this issue with
```css
html,
body {
	-ms-touch-action: none;
}
```
</span>

<span is-issue-template></span>

**Comment by oliversalzburg** [comment]
Also, your issue creating tool doesn't like fenced code blocks ;)

**Comment by oliversalzburg** [comment]
Sadly, once you focus an input box, the view is scrolled up and with our "fix" you're not able to scroll it down again :P

**Comment by oliversalzburg** [comment]
`shell:SystemTray.IsVisible="False"` seems to resolve this issue. I don't know where the height of the tray is falsely taken into account, but hiding it helps.

**Comment by perrygovier** [comment]
Hey @oliversalzburg does this commit help? 26361d653979ba3d345772997b3c13ca038d8532

**Comment by oliversalzburg** [comment]
@perrygovier Seems weird that it would have an impact, but it could be worth a shot.

However, we've already learned to work around the issue by moving to a fullscreen layout and I'm not currently set up to quickly test the proposed change.

**Comment by oliversalzburg** [comment]
I just looked into our application CSS and found the following in the history:

```css
@-ms-viewport {
	width     : device-width;
	height    : device-height;

	user-zoom : fixed;
	max-zoom  : 2;
	min-zoom  : 2;
}
```

I was playing around with those settings to see if they would fix this behavior. Given that they didn't make it into our product, I doubt they had any effect on the issue.
