### ISSUE TITLE
feat: .no-padding class (and others) needed to remove default padding

### ISSUE THREAD

**Issue by MatthiasDebaere** [driftyco/ionic#3186]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>**Problem:** A lot of classes/directives/elements have a default padding in Ionic. Ionic also provides classes to add padding (-left/-top/-bottom/-right) to those that don't have a default padding. (It seems you guys really like your padding!)

**Solution:** because I wanted an easy way to remove this padding I created the class .no-padding
```css
.no-padding {
  padding: 0px; }
```
I also created some extra classes to remove and set padding strictly to top, bottom, left or right. 
```css
.padding-top-only, .padding-vertical-only {
  padding-top: 10px; 
  padding-right: 0px; 
  padding-bottom: 0px; 
  padding-left: 0px; }

.padding-right-only, .padding-horizontal-only {
  padding-top: 0px; 
  padding-right: 10px; 
  padding-bottom: 0px; 
  padding-left: 0px; }

.padding-bottom-only, .padding-vertical-only {
  padding-top: 0px; 
  padding-right: 0px; 
  padding-bottom: 10px; 
  padding-left: 0px; }

.padding-left-only, .padding-horizontal-only {
  padding-top: 0px; 
  padding-right: 0px; 
  padding-bottom: 0px; 
  padding-left: 10px; }
```
And I went a bit all out with it and created combinations of these:
```css
.padding-left-and-right-only {  
  padding: 0px 10px; }

.padding-top-and-bottom-only {
  padding: 10px 0px; }
```

I find this very useful and if you do too, perhaps you can add it (or something like it) in a next update?</span>

<span is-issue-template></span>
