### ISSUE TITLE
bug: Tab bar misplaced when nav bar is hidden

### ISSUE THREAD

**Issue by vchav73** [driftyco/ionic#3266]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>browser</span>

<span ionic-description>I have a nav bar and tabs. I want to hide the nav bar for a certain view in one of the tabs. I set hide-nav-bar="true" for the ion-view. The space for the nav bar still shows, it's just blank with the tab bar below it. I've seen the problem on Android browsers, a native hybrid app (using the CrossWalk client), and a Chrome desktop browser when emulating various Android devices. I'm using the nightly build. See http://codepen.io/anon/pen/azaMMg.

![cp1](https://cloud.githubusercontent.com/assets/2886165/6569918/6acf5d52-c6af-11e4-9fcc-327f4c0d5406.jpg)

<span is-issue-template></span>

**Comment by mhartington** [comment]
There is a css solution to this

```css
.nav-bar-tabs-top.hide +view-container > .tabs-top > .tabs, tabs.tabs-top {
  top: 0; 
}

.nav-bar-tabs-top.hide +view-container > .tabs-top > .tab-content .pane .has-tabs-top {
  top: 49px;
}
```

I don't to add and introduce any new css bugs. Post 1.0, we will be moving thing thing to flex box, so something like this wont be a problem.

**Comment by vchav73** [comment]
I made the CSS addition you suggested (http://codepen.io/anon/pen/EadqNB) but the problem persists. Any other suggestions besides waiting for 1.1?

**Comment by mhartington** [comment]
My mistake, messed up the css selectors.

http://codepen.io/mhartington/pen/OPaLKK

```css
.nav-bar-tabs-top.hide + .view-container > .tabs-top > .tabs, .tabs.tabs-top {
  top: 0 !important; 
}

.nav-bar-tabs-top.hide + .view-container > .tabs-top > .tab-content .pane .has-tabs-top {
  top: 49px !important;
}
```
