### ISSUE TITLE
bug: .has-header "top" property overridden by .pane

### ISSUE THREAD

**Issue by dylansmith** [driftyco/ionic#3330]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi there

I'm working on an app using [ionic-starter-sidemenu](https://github.com/driftyco/ionic-starter-sidemenu), and have a content page that uses tabs. I'm experiencing an issue where the scrollable content area of each tab is aligned `top:0`, and is therefore behind the `<ion-header-bar>`. 

I first noticed this while developing on desktop. It does not occur on iOS, and on Android (native hybrid) it is even worse as the tabs are positioned below the header bar and they overlap further content.

My template is as follows:

```html
<ion-view view-title="Rounds history">
  <ion-tabs tabs-type="tabs-icon-only">
    <ion-tab title="My rounds" icon-on="ion-ios-person" icon-off="ion-ios-person-outline">
      <ion-content class="has-header">
        <rounds-list rounds="ctrl.userRounds"></rounds-list>
      </ion-content>
    </ion-tab>
    <ion-tab title="All rounds" icon-on="ion-ios-people" icon-off="ion-ios-people-outline">
      <ion-content class="has-header">
        <rounds-list rounds="ctrl.allRounds"></rounds-list>
      </ion-content>
    </ion-tab>
  </ion-tabs>
</ion-view>
```

The issue here is that the `<ion-content class="has-header">` directive renders out as `<ion-content class="has-header pane tab-content scroll-content ionic-scroll has-tabs" nav-view="active">`, and `.pane { top: 0, ... }` is overriding `.has-header { top: 44px, ...}` causing the element to be aligned `top:0`.

I believe there may be a need to update the `.has-header` definition in  `_scaffolding.scss` to:

```scss
.has-header {
  top: $bar-height;
  &.pane{
    top: $bar-height;
    height: auto;
  }
}
```

This mirrors what is done for `.has-tabs` in the same file:

```scss
.has-tabs,
.bar-footer.has-tabs {
  bottom: $tabs-height;
  &.pane{
    bottom: $tabs-height;
    height:auto;
  }
}
```

I'm happy to create the pull request if you wish.</span>

<span is-issue-template></span>
