### ISSUE TITLE
bug: 1.0.0-rc.1: Popover + header-bar with top padding on iOS

### ISSUE THREAD

**Issue by ohh2ahh** [driftyco/ionic#3356]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Header-bars in popovers have a top padding on iOS and 1.0.0-rc.1. I suppose that Ionic wants to add this space for the iOS status bar.

```html
// $ionicPopover example with header-bar
<ion-popover-view>
    <ion-header-bar>
        <h1 class="title">My Popover Title</h1>
     </ion-header-bar>
    <ion-content>
        Hello!
    </ion-content>
</ion-popover-view>';
```
Codepen: http://codepen.io/anon/pen/vEvXWL

![popover](https://cloud.githubusercontent.com/assets/2352329/6735525/0d5d5f0e-ce5f-11e4-9b3f-ca5612699be1.png)

Steps to reproduce:
```
$ ionic start myApp http://codepen.io/anon/pen/vEvXWL
$ cd myApp
$ ionic platform add ios
$ ionic build ios
$ ionic emulate ios
```

My system:
* OSX 10.10.2
* Ionic 1.3.16
* Cordova 4.3.0
* tested on iOS 8.1 (simulator) and iOS 8.2 (simulator & device)</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
thx

**Comment by mhartington** [comment]
I have a fix for this.

```css
  .popover{
    .bar-header:not(.bar-subheader) {
      height: $bar-height;
      &.item-input-inset .item-input-wrapper {
        margin-top: -1px;
      }
      > * {
        margin-top: 0;
      }
    }
    .has-header,
    .bar-subheader {
      top: $bar-height;
    }
    .has-subheader {
      top: $bar-height + $bar-subheader-height;
    }
  }
```
Feel free to use this in your app, I will commit it to our post 1.0 branch. I don't want to accidentally break anything with this so we'll wait until post 1.0 to test this more.
