### ISSUE TITLE
bug: ion-nav-bar hide-nav-bar="true" affects all views

### ISSUE THREAD

**Issue by nickcmaynard** [driftyco/ionic#3708]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The has-header class is added/removed from all views during transition, not just from the view with the hidden header.

This causes a layout call to a view that shouldn't be affected.

This issue can be seen easily here:
http://codepen.io/mhartington/pen/qEgRLK

When "Scientific facts" is clicked, the content of the Home view "jumps" up as its padding is removed.

has-header should continue to be applied to views that do not have hide-nav-bar="true". 

To work around this in the short term, I've used these CSS rules:
```css
/* Work around issue with flickering while showing/hiding the nav bar */
ion-nav-view ion-view:not([hide-nav-bar="true"]) ion-content {
    top: 44px;
}
ion-nav-view ion-view[hide-nav-bar="true"] ion-content {
    top: 0;
}
.platform-ios.platform-cordova:not(.fullscreen) ion-nav-view ion-view:not([hide-nav-bar="true"]) ion-content {
    top: 64px;
}
.platform-ios.platform-cordova:not(.fullscreen) ion-nav-view ion-view[hide-nav-bar="true"] ion-content {
    top: 22px;
}
```
</span>

<span is-issue-template></span>
