### ISSUE TITLE
feat: Sidemenu transitions

### ISSUE THREAD

**Issue by ruffiem** [driftyco/ionic#3921]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>Hey,

This is not an issue but definitely could be a very interesting enhancement. I've tried to make a directive to change the behaviour of the sidemenu toggle but I couldn't achieve it since it's a mixture of javascript (dragging the pane) and css (menu-animated).

Wouldn't it be nice to have it either full JS or full CSS ?

For inspiration http://tympanus.net/Development/SidebarTransitions/

The sideMenuController.getOpenRatio() is just useless when clicking the stack button. It returns 0 or 1. That's not quite a ratio, that a status.</span>

Add this to your scss :

```css

.menu-animated, .slide-along {
	@include transition(500ms);
}

.slide-along {
	width: 100% !important;
	@include translate3d(-10%, 0px, 0px);

	h1, h2, h3 {
		max-width: 275px;
	}
}

body.menu-open .slide-along {
	@include translate3d(0, 0, 0);
}
```

and this to your menu template :

```html

<ion-side-menu side="left" class="slide-along">
        <ion-header-bar class="bar-stable">
            <h1 class="title"><!-- Menu --></h1>
        </ion-header-bar>
        <ion-content>
            <ion-list>
                <ion-item menu-close href="#/app/search">Search</ion-item>
                <ion-item menu-close href="#/app/browse">Browse</ion-item>
                <ion-item menu-close href="#/app/playlists">Playlists</ion-item>
                <ion-item menu-close ng-click="login()">Login</ion-item>
            </ion-list>
        </ion-content>
    </ion-side-menu>

```

It looks nice isn't it ? But doesn't work when grabbing the panel :( 

<span is-issue-template></span>
