### ISSUE TITLE
bug: I found unnecessary css code in ionic.css

### ISSUE THREAD

**Issue by EricDosReis** [driftyco/ionic#4181]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys!

I found this unnecessary css code in ionic.css, line 8417.

```css
.button-clear {
  -webkit-transition: opacity 0.1s;
  transition: opacity 0.1s;
  padding: 0 6px;
  max-height: 42px;
  border-color: transparent;
  background: none;
  box-shadow: none; }
  .button-clear.button-clear {
    border-color: transparent;
    background: none;
    box-shadow: none;
    color: #b2b2b2; }
```

Why .button-clear.button-clear?</span>

<span is-issue-template></span>
