### ISSUE TITLE
feat: side-menu-content width from a container

### ISSUE THREAD

**Issue by igorprado** [driftyco/ionic#4478]
**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,

I'm trying to wrap my application in a `div` where, in larger screens, I'm setting a different `width`, like so:

*index.html*
```html
<div class="app-container">
     <ion-nav-view></ion-nav-view>  
</div>
```

```css
.app-container {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	width: 100%;
	margin-left: auto;
	margin-right: auto;

  @media (min-width: 890px) {
    width: 890px;
  }

}
```

I'm using `ion-side-menus`, but when I have larger screens and match the rule above, my `ion-side-menu-content` is getting larger and I think it's because it's using `$window.innerWidth` as listed here: https://github.com/driftyco/ionic/blob/master/js/angular/directive/sideMenuContent.js#L150

Idk if there is another way to accomplish what I want to do, but I thought maybe we can pass a reference of the container to this directive, so it can use when creating the element styles.</span>

<span is-issue-template></span>
