### ISSUE TITLE
ion-slides and ion-slide-page in ionic : 1.2.4

### ISSUE THREAD

**Issue by t0mm13b** [driftyco/ionic#5781]
Ion slides do not show, due to height being set to 0px!

Override it by setting this in CSS:

```css
div.swiper-container-horizontal{
height: 100px;
width: 100px;
}
```
