### ISSUE TITLE
bug: ion-content has always a vertical scroller

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic#6022]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span> beta.3

**Platform**: <span ionic-platform>all</span>  

`<ion-content>` always contains `<scroll-content>` which has
```css
scroll-content {
  overflow-y: scroll;
}
```
so the vertical scrollbar is always visible in `ion-content`.

Suggesttion:
- Should be better to set `overflow-y` to `'auto'`
- Scrollbars of `<ion-content>` should be configurable as in ionic1

**Comment by asanin-2sol** [comment]
+1, is there a reason for it being 'scroll' instead of 'auto'?

**Comment by cesar-oyarzun-m** [comment]
hi @mpaland I have the same problem I see vertical scroll in all my screens, do you have a work around?

**Comment by iignatov** [comment]
@cesar-oyarzun-m As a workaround you could add the following in the application's `app.core.scss`:

```css
scroll-content {
	overflow-y: auto !important;
}
```
