### ISSUE TITLE
iOS: duplicated border if multiple toolbars in ion header 

### ISSUE THREAD

**Issue by DavidWiesner** [driftyco/ionic#7119]
#### Short description of the problem:
If I put multiple toolbars in an ion-header there is an border between this toolbar

#### What behavior are you expecting?
No Border between the toolbars

**Steps to reproduce:**
See Plunkr http://plnkr.co/edit/7trkahTuBd6xK9Rx7kNs?p=preview

#### Here is a workaround
```css
.ios .toolbar-background:last-of-type{
  border-bottom-width: 1px;
}

.ios .toolbar-background:first-of-type{
  border-top-width: 1px;
}


.ios ion-header .toolbar .toolbar-background{
  border-top-width: 0;
  border-bottom-width: 0;
}
```
##### Versions
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.5 (jessie) 
Node Version: v5.12.0
