### ISSUE TITLE
Horizontally Scrollable ion-tabs

### ISSUE THREAD

**Issue by chiragandroid** [driftyco/ionic#7202]
**Here I am requesting a new feature in ionic1 that is Horizontally Scrollable IONIC TAB**

Actually, in ionic forms there is a lot of question on this topic some of that I am mentioning here. 

[By Rakesh Gajjar](https://forum.ionicframework.com/t/how-to-make-horizontal-scrollable-tab-nav-i-have-got-more-then-5-ion-tab/15088)
[many more](https://forum.ionicframework.com/search?q=scrollable%20ion-tab)

When we put too many ion-tab in ion-tabs . all tab text end by ...  
![menu](https://cloud.githubusercontent.com/assets/11516494/16575510/76dfba00-42a6-11e6-8ade-55d5d416e11a.png)

so please make some feature that makes ionic tabs scrollable in ion-tabs.

Thank you.

**Comment by InfinityOne** [comment]
```scss

ion-segment {
    justify-content: space-between;
    overflow: auto;

    &::-webkit-scrollbar {
        width: 0;
        height: 0;
        display: none;
    }

    ion-segment-button.segment-button {
        flex: 1 0 100px;
    }
}

```
