### ISSUE TITLE
bug: [Bug] App layout broken after closing the keyboard

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic#7789]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

More info from Team Viewer Quick Support:

![image](https://cloud.githubusercontent.com/assets/9698639/17824929/77660018-662a-11e6-9b98-2c77b959ba2a.png)

<span ionic-description>

This issue is a weird one, one of our customers happened this while working with our app with Ionic 2-beta.10:</span>

![image](https://cloud.githubusercontent.com/assets/9698639/17824891/40c31dfc-662a-11e6-95a3-32a323857d7d.png)

<span is-issue-template></span>

**Comment by Luchillo** [comment]
Here's the original layout, the image above in issue description is after i open the keyboard by clicking in an Input and then closing the keyboard by clicking away of Input:
![image](https://cloud.githubusercontent.com/assets/9698639/17825000/ca5f6106-662a-11e6-9bde-60708f095a7a.png)

**Comment by Luchillo** [comment]
I've tested in 2 different devices and it doesn't happen, so i think is an issue with that exact device, idk how to test if i don't own the device.

**Comment by Luchillo** [comment]
I'm finally able to replicate in my Galaxy tab A with Android 5.0.2 model SM-P555M, after testing this was the issue:
```scss
body {
  left: 50%;
  max-width: 1024px;
  transform: translateX(-50%);
}
```

For some reason the `left: 50%;` was breaking the responsiveness i have put to be able to use the app even in the browser, the fix? here:
```scss
body {
  top:  0;
  left: 50%;
  max-width: 1024px;
  transform: translateX(-50%);
}
```
Just adding the `top` propery with `0` as value
