### ISSUE TITLE
addScrollListener handler has incorrect context

### ISSUE THREAD

**Issue by dudeofawesome** [driftyco/ionic#7994]
#### Short description of the problem:
The handler method for `content.addScrollListener` has incorrect context.

#### What behavior are you expecting?
I expect handler method to have the `Page`'s context, not the `scroll-content`'s HTML element context

```Typescript
@Component({
  template: `
    <ion-header></ion-header>
    <ion-content padding>
    </ion-content>
  `,
})
export class JobPage implements AfterViewInit {
  @ViewChild(Content) content: Content;

  ngAfterViewInit () {
    this.content.addScrollListener(this.scroll);
  }

  scroll () {
    console.log(this.content.contentTop); // will throw "TypeError: Cannot read property 'contentTop' of undefined"
  }
}
```

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```YAML
Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```
