### ISSUE TITLE
Two buttons in ion-nav-buttons side right on Android 4.4

### ISSUE THREAD

**Issue by dovidkopel** [driftyco/ionic#930]
With two buttons in my `ion-nav-buttons` tag with `side="right"` the second button is not floated properly, and goes goes into the content.

I have the "exact" same app running on the same phone model but it is working. Not sure why this is happening intermittently.

![screenshot_2014-03-27-12-40-29](https://cloud.githubusercontent.com/assets/1078458/2540032/a8e3fc94-b5ce-11e3-86cb-7cd16df35137.png)

**Comment by webfacebg** [comment]
```css
.platform-android .secondary-buttons button,
.platform-android .primary-buttons button {
                                            float: left;
                                            }
```
That works for me as a temporary solution.
